name    'NexusIS-gerrit'
version '1.0.0'
author 'aimonb'
license 'Apache 2.0'
summary 'Web based code review and project management for Git based projects. '
description 'Gerrit is a web based code review system, facilitating online code reviews for projects using the Git version control system.'
project_page 'https://code.google.com/p/gerrit/'

dependency 'puppetlabs/stdlib', '>= 3.2.1'
dependency 'puppetlabs/mysql', '>= 2.2.1 < 2.2.2'
dependency 'puppetlabs/apache', '>= 0.4.0'
