name    'aimonb/nexusis_gerrit'
version '1.1.1'
author 'aimonb'
license 'Apache 2.0'
summary 'Web based code review and project management for Git based projects. '
description 'Gerrit is a web based code review system, facilitating online code reviews for projects using the Git version control system.'
project_page 'https://code.google.com/p/gerrit/'

dependency 'puppetlabs/stdlib', '>= 3.2.1'
dependency 'puppetlabs/mysql', '>=0.6.1 <1.0.0'
dependency 'puppetlabs/apache', '>= 0.4.0'
dependency 'puppetlabs/inifile', '>=1.0.0 <2.0.0'
